-- [1] 기존 구조 초기화 (새로 시작할 때를 대비)
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.survey_responses;
DROP TABLE IF EXISTS public.profiles;

-- [2] profiles 테이블 생성 (사용자 정보)
-- 가입 시 유연함을 위해 name과 email의 NOT NULL 제약을 해제한 최신 버전입니다.
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE,
  name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- [3] survey_responses 테이블 생성 (설문 응답)
CREATE TABLE public.survey_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  q1 TEXT NOT NULL,
  q2 TEXT[] NOT NULL,
  q3 TEXT NOT NULL,
  q4 TEXT[] NOT NULL,
  q5 TEXT, -- 서술형 문항
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- [4] RLS(보안 정책) 활성화
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.survey_responses ENABLE ROW LEVEL SECURITY;

-- [5] profiles 테이블 보안 정책
-- 가입 시 세션이 없는 상태에서도 프로필 생성이 가능하도록 허용 (500 에러 방지)
CREATE POLICY "Allow all inserts for signup" 
ON public.profiles FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Allow all selects for app" 
ON public.profiles FOR SELECT 
USING (true);

-- [6] survey_responses 테이블 보안 정책
-- 본인의 응답만 저장하고 본인의 응답만 볼 수 있도록 설정
CREATE POLICY "Users can insert their own responses" 
ON public.survey_responses FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own responses" 
ON public.survey_responses FOR SELECT 
USING (auth.uid() = user_id);

-- [7] 관리자 전용 정책 (선택 사항)
-- 본인의 관리자 이메일을 정확히 입력하세요.
CREATE POLICY "Admins can view everything" 
ON public.survey_responses FOR SELECT 
USING (auth.jwt() ->> 'email' = 'your-admin-email@example.com');



-- -- ⚠️ 세팅 시 주의사항 (Dashboard 설정)
-- -- SQL 실행 외에 Supabase 대시보드에서 반드시 아래 설정을 수동으로 변경해야 앱이 정상 작동합니다:
-- -- Email Confirmation 비활성화:
-- -- Authentication -> Providers -> Email -> Confirm email을 OFF로 설정.
-- -- 이게 켜져 있으면 가입 즉시 로그인이 안 되어 설문 작성이 불가능해집니다.
-- -- 환경 변수(Vite):
-- -- 반드시 eyJ...로 시작하는 긴 Anon Key를 사용하세요.


-- 💡 팁: 데이터 초기화가 필요할 때
-- 개발 중에 모든 유저와 데이터를 밀고 다시 시작하고 싶다면 아래 명령만 실행하면 됩니다.

-- -- SQL
-- --   TRUNCATE public.survey_responses CASCADE;
-- --   TRUNCATE public.profiles CASCADE;
-- --   DELETE FROM auth.users;








-- 기존의 제한적인 SELECT 정책을 삭제합니다.
DROP POLICY IF EXISTS "Users can view their own responses" ON public.survey_responses;
DROP POLICY IF EXISTS "Admins can view everything" ON public.survey_responses;

-- 모든 인증된 사용자가 모든 응답을 볼 수 있도록 허용 (관리자 전용 페이지이므로)
CREATE POLICY "Enable read access for all authenticated users" 
ON public.survey_responses FOR SELECT 
TO authenticated 
USING (true);


-- 기존의 삭제 정책이 있다면 삭제
DROP POLICY IF EXISTS "Enable delete for authenticated users" ON public.survey_responses;

-- 모든 인증된 사용자가 설문 응답을 삭제할 수 있도록 허용
-- (더 보안을 강화하려면 특정 관리자 이메일 조건 'auth.jwt() ->> email = ...'을 넣을 수 있습니다)
CREATE POLICY "Enable delete for authenticated users"
ON public.survey_responses
FOR DELETE
TO authenticated
USING (true);